### ISSUE TITLE
CI/CD: latest release and snapshot tags in docker images

### ISSUE THREAD

**Issue by mariannovotny** [G-Research/siembol#135]
We would like to  distinguish between lastest built docker images from SNAPSHOT and latest docker images from release versions  that should be stable. We can not guarantee stability of snapshot versions.

Config editor ui unstable versions should contain suffix 'dev' and java snapshots have suffix 'SNAPSHOT'. Latest docker images for these version should include the tag  'latest'. Latest docker images for release versions should include the tag 'stable'.

**Comment by jgiannuzzi** [comment]
After letting this sit with me for a bit, I wonder whether we might not instead use `latest` for release versions (like today) and `snapshot` or `dev` for the non-release versions.
In the Docker world, `latest` is what you get when you don't specify a tag, and it's usually assumed it will be the latest stable version. Changing that to mean the _literal_ latest could be confusing.

What are your thoughts, @mariannovotny?

**Comment by mariannovotny** [comment]
I am OK with 'latest' (release version) and 'snapshot' for non release versions. Thanks for improving specs.

**Comment by ljubon** [comment]
hellou @mariannovotny @jgiannuzzi, as an example I would like to suggest the following change (my local PR just for the demo I did it for config-editor-ui) - https://github.com/ljubon/siembol/pull/1/files

In order to avoid confusion please note that we don't want to change the current maven/java versioning `X.Y.Z-SNAPSHOT` for snapshot/dev/nightly build and `X.Y.Z` for the official release 🙏 

So I would like to focus here only on how we do `TAG`-ing of your docker images
As you already confirmed you want `LATEST` for the release version and `SNAPSHOT` for non-release versions for your docker images. 
I did example that example in my PR above
p.s I did commands on my local machine just to get current status and to see how to adopt it, so feel free to write me some inputs if I did some bad formating 💪

**Comment by mariannovotny** [comment]
Hi @ljubon Thanks for your suggestions. 

Can I ask you why do you suggest to replace 'dev' by 'SNAPSHOT' in config-editor-ui? We can use directly SNAPSHOT but let me note that versioning ui dev/snapshot releases is not synced with java versioning of snapshots - only version of releases are synced. This way we are using 'dev' instead of 'SNAPSHOT' if it makes sense?

**Comment by ljubon** [comment]
hi @mariannovotny, I did for `config-editor-ui` just as example so we are all on the same page with changes 
I understood that we want to implement following:

- when a 'stable' release is done, tag as latest
- when an 'unstable' release is done, tag as snapshot

and this is only for releasing docker images, we don't want to change release process for regular maven/java versioning?

**Comment by mariannovotny** [comment]
Hi, @ljubon Yes we do not want to change maven/java versioning just docker image tags. We would like to implement in docker images:

- when a 'stable' release is done, tag as latest + tag with version from pom (java) or appVersion frombuild-info.json for UI
- when an 'unstable' release is done, tag as snapshot  + tag with version from pom (java) or appVersion frombuild-info.json for UI

**Comment by ljubon** [comment]
> Hi, @ljubon Yes we do not want to change maven/java versioning just docker image tags. We would like to implement in docker images:
> 
> * when a 'stable' release is done, tag as latest + tag with version from pom (java) or appVersion frombuild-info.json for UI
> * when an 'unstable' release is done, tag as snapshot  + tag with version from pom (java) or appVersion frombuild-info.json for UI

hellou @mariannovotny , thanks for putting additional info here! 🙏 
let me formulate my questions differently, what makes a build 'stable'? which conditions need to be met?
from `ci.yaml` i can say it simple as this:
`    if: github.event_name == 'push' && !github.event.repository.fork && ( github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/hotfix/') )`
please comment/confirm this

in addition, I would suggest using unique versioning (from java) but that is a big change I we need to think about compatibility?with current setup (not affecting current setup)

**Comment by mariannovotny** [comment]
Hi @ljubon . The build is stable if it is release from master or hotfix branch (the condition form your comment) and if java version in pom file does not contain 'SNAPSHOT' and angular app does not contain 'dev' in version.

Using unique version is something that can simplify something on the other hand it will complicate developing ui as in java you need to change all submodules version - look https://github.com/G-Research/siembol/pull/63/files and we do nto have automated this process yet.

This way we pragmatically decide to have unique version for releases (stable versions) and snapshots/dev minors can diverge because it is developed in separated PRs. Therefore we are using 'dev' instead of SNAPSHOT to avoid confusion.

**Comment by jgiannuzzi** [comment]
It sounds like the implementation should essentially be:
- add a step to each `build-docker-*` job that 'computes' whether this is a `latest` or a `snapshot`
- change the `meta` step of each of those jobs to add an extra raw tag with the computed value
- disable the `latest` flavor on those `meta` steps (to be validated whether docker/metadata-action can cope with that)

**Comment by ljubon** [comment]
@jgiannuzzi if I may ask, why should we `disable the 'latest' flavor on those 'meta' steps (to be validated whether docker/metadata-action can cope with that)`?
If we publish the release version we want to publish X.Y.Z (default) + LATEST (new) tags? I understand that we don't want to discard current versioning just to provide improvements in a way of adding new tags latest or snapshot
I did a new push/implementation, feel free to give feedback  ⚡ 
https://github.com/ljubon/siembol/pull/1/files @mariannovotny you too 🙏

**Comment by ljubon** [comment]
FYI I opened draft PR, feel free to put comments ⚡  https://github.com/G-Research/siembol/pull/226

**Comment by jgiannuzzi** [comment]
Implemented in #226

**Comment by mariannovotny** [comment]
I think we forgot to update documentation https://github.com/G-Research/siembol/blob/master/docs/deployment/deployment.md - I will do it before next release.
