### ISSUE TITLE
Alerting: Add "Contains" Matcher

### ISSUE THREAD

**Issue by g-airey** [G-Research/siembol#420]
Request: Add a new "contains" matcher that searches for a specific substring in a given value

Being able to query for a specific substring (e.g. "`user`" in "`test_user_1`") would be very useful as this is something that we use regex for regularly.  We could also use this to search using variables that were extracted using regex matching groups.

Potentially also add this to `IS_IN_SET`, so we can have multiple of these in a single matcher.

This should also have the standard SIEM setup of: "starts with", "ends with" or "contains" so that we can define how it should match.

**Comment by mariannovotny** [comment]
The matcher will have these flags with default values:
"case_insensitive":false,
"starts_with":true,
"ends_with":true
